import Head from 'next/head';

import { MainContext } from '@/state';
import styles from '@/styles/Home.module.scss';
import MainLayout from '@/layouts/MainLayout/MainLayout';
import { useReducer } from 'react';
import { mainReducer } from '@/state/reducers';
import { mockTodos, tTodo } from '@/mock/todos';
import Maininput from '@/components/mainInput/Maininput';
import Todo from '@/components/todo/Todo';


export default function Home({ todos }: any) {
  // VARIABLES ------------------
  const [state, dispatch] = useReducer(mainReducer, todos);
  // CONDITIONS -----------------
  // FUNCTIONS ------------------

  // RETURN ---------------------
  return (
    <>
      <Head>
        <title>Todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
        <MainLayout>
          <main className={`${styles.Home}`}>
            <Maininput />
            <h1>Home</h1>

            {state.map((todo: tTodo, index: number) => {

              return (
                <Todo data={todo} key={index} />
              )
            })

            }

          </main>
        </MainLayout>
      </MainContext.Provider>

    </>
  )
}


export async function getServerSideProps(context: any) {
  const todos: tTodo[] = mockTodos;
  return {
    props: {
      todos
    }
  }
}
